name: Deploy to Production

on:
  push:
    branches:
      - pre-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploying Application
        uses: appleboy/ssh-action@master
        with:
          script: |
            docker stop crw_app
            cd ${{ secrets.APPLICATION_PATH }}
            git pull origin master
            docker start crw_app
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
